# inherit_from: rubocop_todo.yml

AllCops:
  Rails:
    Enabled: true
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'test/test_helper.rb'
    - 'test/support/**/*'
    - 'test/dummy/**/*'

HasAndBelongsToMany:
  Enabled: false

Documentation:
  Enabled: false

MethodDefParentheses:
  Enabled: false

GuardClause:
  Enabled: false

RedundantSelf:
  Enabled: false

LineLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 13

Metrics/ModuleLength:
  Max: 110

Metrics/AbcSize:
  Max: 16
  
